### PR TITLE
Prevented duplicated records to improve populating performance.

### PR DESCRIPTION
**Pull request by jianpingw**
This commit is to fix the slow population (and big memory usage) problem as described in:
balderdashy/sails-mysql#161

### CODE REVIEW

**Comment by devinivy** [comment]
I believe `findIndex` is also O(N) (though much quicker, of course, than the work waterline is doing).  Could we keep track of the records that have been added to the array in a dictionary (indexed by primary key)?  If you don't want to change this, then that's okay and we can make further improvements later :)

**Comment by jianpingw** [comment]
@devinivy yes, good point. I will improve it using dictionary.

**Comment by jianpingw** [comment]
In addition to use dictionary to improve search performance, I also fixed the primary key, it should be `childVal` instead of `pk`.

**Comment by irlnathan** [comment]
Thanks @jianpingw for submitting this.  Since this deals with performance, it would be great to have a baseline to compare against. So basically a script we can run (maybe a test) that provides a benchmark before and after the patch.  Many thanks!

**Comment by devinivy** [comment]
@irlnathan the waterline-adapter-tests repo has a baseline for perf somewhere!

**Comment by particlebanana** [comment]
Been playing with this patch all morning and it's great! Posted more info here: https://github.com/balderdashy/sails-postgresql/pull/224.

I'll get a patch published shortly.

**Comment by particlebanana** [comment]
The project @jianpingw created shows the performance before and after the patch. https://github.com/jianpingw/wl-perf

**Comment by mikermcneil** [comment]
@jianpingw Awesome!  Appreciate all your work on making the `wl-perf` repo, I think this will help us a lot on future optimizations to Waterline and our adapters, and it also gives us a great way to validate your patch to this adapter and to sails-postgresql (as well as future patches from the community).

I noticed that you documented the performance of a particular test case in the README:

> The find messages test case takes about 3 seconds on a Core i3-3110M (2.4GHz) HP laptop (the database has zero row before running the test case).

I'm guessing it was postgresql, but would you mind clarifying which adapter was being used (postgres vs. mysql) in the test case?  Also, re: this PR, would you document the performance increase that results from this patch and your patch in sails-postgresql?  As you know Sails and Waterline have grown a lot in the past couple of years, and as a matter of process, we want to make sure we have clear proof (which you've set up the foundation for) as well as documentation on the background and reasoning for patches to core and officially supported adapters such as sails-mysql.  Again, thanks so much!  Looking forward to merging this in.

**Comment by devinivy** [comment]
@mikermcneil it's worth checking out the work that has been done on benchmarking in the past as well.  wl-perf is very useful, but I personally prefer benching waterline without sails being in the mix.  Here's what we currently have: https://github.com/balderdashy/waterline-adapter-tests/tree/master/test/load

**Comment by mikermcneil** [comment]
@devinivy It's definitely a good idea to get benchmarks with as few variables as possible (of course, having higher level benchmarks as a sanity check certainly doesn't hurt either).  I hadn't checked back in on the progress on the load tests built in to wl-adapter-tests- thanks for the heads up!  Looks awesome; and nice and easy to run.

Regardless of the approach taken, when someone has time to run some benchmarks and document the performance with and without this patch as a comment on this PR, then we'll get this merged and start taking advantage of it ASAP (same thing for the related PR to sails-postgresql).

**Comment by jianpingw** [comment]
@mikermcneil I have updated `wl-perf ` README to document the performance increase resulted from this patch.

I will run same benchmark for MySQL adapter (already did so for postgresql  and added the result to the PR).

**Comment by jianpingw** [comment]
For this test case (with sails-mysql adapter):
https://github.com/jianpingw/wl-perf

The find messages test case took about 2800ms on a Core i3-3110M (2.4GHz) HP laptop (the database has zero row before running the test case) before this patch.

With this patch, the same test case took about 200ms.

**Comment by mikermcneil** [comment]
@jianpingw you the man

**Comment by Zaggen** [comment]
I agree with @devinivy , and would be nice to have a comparison before and after the change but performing an isolated test that does not include sails (Only waterline) and put it here as a reference?. Anyways, like i said before, awesome job :)

**Pull request merged**
