### PR TITLE
fix populate on different connections

### PR DESCRIPTION
**Pull request by kai23**
That's what we use to avec multiple connections with table which have the same name.

Basically, we restrict the schema used to match only the connection we should use.

### CODE REVIEW

**Comment by dmarcelino** [comment]
This can be related to balderdashy/waterline#925 (more specifically https://github.com/balderdashy/waterline/issues/925#issuecomment-89614487). I wonder if this is only broken for sails-mysql or if it's a more global issue... We should add a multiple connection (same DB) test to waterline adapter tests and assess. We will need it anyway to confirm this fix works.

**Comment by dmarcelino** [comment]
And BTW, thanks @kai23! :)

**Comment by kai23** [comment]
Oh you're welcome, it's my first pull request ever and I'm glad it's for the sails community :)

**Comment by particlebanana** [comment]
Is this still an issue? And if so can this be resubmitted with an updated patch and test?

**Pull request closed without merging**
