### PR TITLE
Send modified schema to work with wl-sql 0.4.0

### PR DESCRIPTION
**Pull request by particlebanana**
Allows for proper use of tableName. 

Should fix https://github.com/balderdashy/waterline/issues/619

### CODE REVIEW

**Comment by dmarcelino** [comment]
Initially I was gonna ask why don't we clean the schema on waterline-sequel but then I noticed that waterline-sequel doesn't have `connectionName` (and it shouldn't as it's not really its responsibility). I'm good with this :white_check_mark:

**Comment by devinivy** [comment]
As I stated on https://github.com/balderdashy/sails-postgresql/pull/158#issuecomment-98565273,
> Given that this schema-cleansing involves a `cloneDeep` and occurs on every query, I think it really ought to be cached per connection.  Otherwise, looks good!

**Comment by devinivy** [comment]
Proposed PR (to be merged into this branch/PR): https://github.com/particlebanana/sails-mysql/pull/1

**Comment by particlebanana** [comment]
@devinivy @dmarcelino I added a commit that moves the schema cleaning to the register connection method. Same code works for both mysql/postgresql and passes all the tests. Once Travis is done I'll merge both of the PR's. With this we don't need the memoize function in https://github.com/particlebanana/sails-mysql/pull/1 and we don't do any cloning.

**Comment by dmarcelino** [comment]
@particlebanana, that sounds good :+1:

**Pull request merged**
