### PR TITLE
Count

### PR DESCRIPTION
**Pull request by particlebanana**
Implement native count method using waterline sequel.

### CODE REVIEW

**Comment by devinivy** [comment]
No `values` to worry about, as in the postgresql PR?

**Comment by particlebanana** [comment]
The MySQL adapter doesn't use parameterized queries so it shouldn't need it. I'll double check real quick though.

**Comment by particlebanana** [comment]
Yeah it inlines the values. Should be good.

**Comment by devinivy** [comment]
:+1:

**Pull request merged**
