### PR TITLE
Fixes #291

### LINKED ISSUE #291: Unnecessary SELECT + UNION queries on populate of one-to-many relationship
Having a one-to-many relationship and populating the one side, sails-mysql generates a SELECT subquerie for every foreign key and combines them by UNION.

A query looks like that one:
```
MySQL.processChildren:  (SELECT * FROM `pet` AS `pet` WHERE `owner` = 1  ORDER BY `pet`.`id` ASC) UNION (SELECT * FROM `pet` AS `pet` WHERE `owner` = 2  ORDER BY `pet`.`id` ASC) UNION (SELECT * FROM `pet` AS `pet` WHERE `owner` = 3  ORDER BY `pet`.`id` ASC) 
```

It would be much faster not to use subqueries - especially if it comes to more foreign keys involved. This query would give the same results:
```
SELECT * FROM `pet` AS `pet` WHERE `owner` IN (1, 2, 3) ORDER BY `pet`.`owner`, `pet`.`id` ASC
```

Is there any reason why the subqueries are used? There aren't any [comments in code](https://github.com/balderdashy/sails-mysql/blob/3b08794a14e7b7f0dedcaab47df1d37458a0430e/lib/adapter.js#L699-L705).

### PR DESCRIPTION
**Pull request by jelhan**
Have a look at #291 for details.

### CODE REVIEW

**Comment by mikermcneil** [comment]
responded re populate usage here: https://github.com/balderdashy/sails-mysql/issues/291#issuecomment-195591840

re: tests, good catch.  Would you mind adding a test to waterline-adapter-tests that fails without your [second commit](https://github.com/jelhan/sails-mysql/commit/b4475f89678b28407c7617087ace8258d922cb6b) from this PR?  

Great stuff, thanks @jelhan!

**Comment by jelhan** [comment]
I'm going crazy with the tests. There is a test in waterline-adapter-tests which should fail for d34d2e06bc24d6aa0f63279b0affea522ba8ef16: https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/associations/hasMany/find.populate.where.js#L82-L113

If I'm checking out d34d2e06bc24d6aa0f63279b0affea522ba8ef16 and running npm test it does not fail. But if I'm running tests from https://github.com/balderdashy/waterline-adapter-tests it fails.

Steps to reproduce:
```
$ git clone git@github.com:balderdashy/sails-mysql.git
$ cd sails-mysql/
$ git checkout d34d2e06bc24d6aa0f63279b0affea522ba8ef16
$ npm install
$ WATERLINE_ADAPTER_TESTS_USER=user WATERLINE_ADAPTER_TESTS_PASSWORD=password WATERLINE_ADAPTER_TESTS_DATABASE=database npm test
...
  Association Interface
    Has Many Association
      .find
        ✓ should return only payments less than or equal to 2
        ✓ should return payments using skip and limit
        ✓ should allow filtering by primary key
...
$ cd ..
$ git clone git@github.com:balderdashy/waterline-adapter-tests
$ npm install --save-dev jelhan/sails-mysql#d34d2e06bc24d6aa0f63279b0affea522ba8ef16
$ npm install
$ node test/integration/runner.js sails-mysql
...
  1) Association Interface Has Many Association .find should return payments using skip and limit:

      Uncaught AssertionError: expected customers[1] to have 2 payments but instead it looks like:
[ add: [Function: add], remove: [Function: remove] ]
      + expected - actual

      -false
      +true
      
      at interfaces/associations/hasMany/find.populate.where.js:99:11
...
$ MYSQL_ENV_MYSQL_USER=user MYSQL_ENV_MYSQL_PASSWORD=password MYSQL_ENV_MYSQL_DATABASE=database nodejs test/integration/runner.js sails-mysql
$ git checkout -f v0.11.1
$ rm -rf node_modules
$ npm install --save-dev jelhan/sails-mysql#d34d2e06bc24d6aa0f63279b0affea522ba8ef16
$ npm install
# setting mysql user, password and database as environment is not possible in v0.11.1, modify test/integration/config/sails-mysql.json instead
$ vi test/integration/config/sails-mysql.json
...
1) Association Interface Has Many Association .find should return payments using skip and limit:

      Uncaught AssertionError: expected customers[1] to have 2 payments but instead it looks like:
[ add: [Function: add], remove: [Function: remove] ]
      + expected - actual

      -false
      +true
      
      at interfaces/associations/hasMany/find.populate.where.js:99:11
...
```

Any idea?

**Comment by jelhan** [comment]
@mikermcneil I rebased against current master. False positive test issue is resolved. Test _Association Interface Has Many Association .find should return payments using skip and limit_ fails on first commit but passes on second one.

**Comment by mikermcneil** [comment]
@jelhan thanks for the follow up- @particlebanana or I will take a look at this today.

**Comment by labmorales** [comment]
Any update on this fix? Any chance it get analysed by you guys any time soon? Thanks!

**Comment by bennotti** [comment]
Any update?

**Comment by Bazze** [comment]
Nothing new here?

**Comment by jelhan** [comment]
@mikermcneil I'm willing to rebase against current master after review. Still waiting for your feedback.

**Comment by jelhan** [comment]
@particlebanana Would love to see this one in next version...

**Comment by mikermcneil** [comment]
@labmorales @bennotti @Bazze @jelhan Really appreciate your patience and continued help. 👍     Quick update: We're planning to merge this PR, plus apply the Sails v1.0 updates by @particlebanana in sails-postresql, when he gets back in town in about a week.  (That way we'll be sure to use the same approach in both adapters.)  I'll update again ASAP.

**Comment by particlebanana** [comment]
@jelhan looks good. Can you cleanup the whitespace issues?

**Comment by jelhan** [comment]
@particlebanana Fixed one whitespace issue. The rest looks fine. Note that newly added `if` increases indentation of existing code.

**Comment by particlebanana** [comment]
Thanks @jelhan

**Comment by mikermcneil** [comment]
@jelhan aside: @particlebanana is working on improving base query building performance on [this branch of sails-postgresql](https://github.com/balderdashy/sails-postgresql/tree/machinepack), but once that's good, he or I will take a pass at incorporating what you did here into the native join function there as well

**Pull request merged**
