### PR TITLE
Return code non zero if any test fails

### PR DESCRIPTION
**Pull request by dmarcelino**
The latests builds are broken, but they still show as OK.

### CODE REVIEW

**Comment by dmarcelino** [comment]
@devinivy, @tjwebb, anything against this one? Not returning error when an error happens is a bit delusional :)

**Comment by devinivy** [comment]
:+1: Looks good

**Comment by tjwebb** [comment]
Weird, are all the adapters like this?

**Comment by dmarcelino** [comment]
I didn't check all, but most of them are.

**Pull request merged**
