### PR TITLE
Add SQL interface

### PR DESCRIPTION
**Pull request by dmarcelino**
Add SQL interface to package.json 
balderdashy/waterline-adapter-tests#40

NOTE: this PR requires waterline-adapter-tests to be released (`0.10.9`).

### CODE REVIEW

**Comment by devinivy** [comment]
:heavy_check_mark: 

What's with the build failure?

**Comment by dmarcelino** [comment]
waterline-adapter-tests haven't been released yet so the tests break while trying to find the sql folder. Once we release we can re-run the tests and we should be good.

**Comment by devinivy** [comment]
D'oh!  Of course.  Ready for merge?

**Comment by dmarcelino** [comment]
Let wait for waterline-adapter-tests `0.10.9` to be released otherwise the build will break.

**Pull request merged**
