### PR TITLE
Promisify .query()

### PR DESCRIPTION
**Pull request by connor4312**
Got tired of doing this manually every time :stuck_out_tongue:. Backwards compatible with callbacks.

### CODE REVIEW

**Comment by connor4312** [comment]
Hold off merging, investigating possible side-effects...

**Comment by connor4312** [comment]
Okay, this will cause errors for people who have manually promisified the .query method.

**Comment by tjwebb** [comment]
Yea, fixing bugs can break workarounds. I think this is ok.

**Comment by connor4312** [comment]
I've manually cloned this branch of sails-mysql into my npm_modules. I'll leave it in for a day or two of development to see if any issues turn up.

**Comment by tjwebb** [comment]
Waterline already supports bluebird promises though. So I'm confused as to what this PR solves.

**Comment by connor4312** [comment]
The direct .query method for executing "raw" SQL didn't support promises. So whenever I wanted to use it, I'd have to manually construct a promise or promisify in every module that it's used.

**Comment by tjwebb** [comment]
Hmm, I didn't realize that. Can you just submit the PR to Waterline repo, then, so it can be fixed for all adapters?

**Comment by connor4312** [comment]
Sure :+1:

**Comment by Globegitter** [comment]
@connor4312 just ran into that as well (with postgresql though). Couldn't find anything on waterline. Did you ever get to it?

**Comment by devinivy** [comment]
+1, this should be supported, especially given that `query` is part of the new SQL interface spec.

**Comment by svenvarkel** [comment]
+1 from here, too. Until then we need to "promisify" manually, I guess?

**Pull request closed without merging**
