### PR TITLE
Also define default value in database

### PR DESCRIPTION
**Pull request by uzyn**
based on `defaultsTo`.

### CODE REVIEW

**Comment by devinivy** [comment]
My only concern here is serialization of values.  For example, if the column type is `json`, then the object in `defaultsTo` needs to become a string.  I think you'll want to appeal to this function for that: https://github.com/balderdashy/sails-mysql/blob/f1e6393295f535ad4f0dbc971d94e681c9eb3864/lib/utils.js#L46

**Comment by uzyn** [comment]
Thanks @devinivy. Just updated the PR.

**Comment by uzyn** [comment]
FYI, TEXT and BLOB columns cannot have default values.
Ref.: https://dev.mysql.com/doc/refman/5.0/en/blob.html

**Comment by devinivy** [comment]
:+1: Looks good.  Someone else want to make a pass over this?  @tjwebb / @dmarcelino ?

**Comment by dmarcelino** [comment]
Looks good to me :white_check_mark: 

BTW @uzyn, thanks for cleaning the code a bit, and for the change :)

**Comment by Tronix117** [comment]
:+1: Any ETA for the merge ?

**Comment by RWOverdijk** [comment]
:+1: I'm waiting for permission to merge. :)

**Comment by particlebanana** [comment]
As answered [here](https://github.com/balderdashy/sails-mysql/pull/229#issuecomment-176442244), while I think it's a good idea to have a default value selected in your database (along with things like `required`), I really want Waterline to be out of the business of migrations. There are some great libraries for defining what the underlying structure of the tables look like such as [Sails Migrations](https://github.com/BlueHotDog/sails-migrations) or [Knex Migrations](http://knexjs.org/#Migrations).

Adding all the database options for every database directly to the attribute, along with validations is just too much.

**Pull request closed without merging**
